#!/bin/bash
usage() {
  echo "usage: $0 CLIENT"
  echo
  echo 'CLIENT: name of client service to generate token for'
}

CLIENT="${1}"
SERVICE="smd"

if [[ -z "$CLIENT" ]]
then
	echo "Empty client"
    usage >&2
	exit 1
fi

echo "Generating bootstrap token for service client ${CLIENT}"
TOKENSMITH_BOOTSTRAP_TOKEN=$(podman exec -e SERVICE=$SERVICE -e CLIENT=$CLIENT tokensmith /bin/sh -c "\
                        /usr/local/bin/tokensmith bootstrap-token create \
                        --bootstrap-store \${TOKENSMITH_RFC8693_BOOTSTRAP_STORE} \
                        --subject \${CLIENT} \
                        --audience \${SERVICE} \
                        --scopes "read" \
                        --output-format json | jq -r '.bootstrap_token'
                        ")

SECRET_NAME="${CLIENT}-bootstrap-token"
echo "Creating secret ${CLIENT}-bootstrap-token"
printf '%s' "$TOKENSMITH_BOOTSTRAP_TOKEN" | podman secret rm -i ${SECRET_NAME} 2>/dev/null || true
printf '%s' "$TOKENSMITH_BOOTSTRAP_TOKEN" | podman secret create ${SECRET_NAME} -